"""Synology Chat channel adapter.

Synology Chat is a team messaging application built into Synology DiskStation
Manager (DSM).  This adapter acts as both:

1. **Outgoing webhook receiver** — an ``aiohttp`` server that Synology Chat
   POSTs to whenever a user sends a message that matches the outgoing webhook
   trigger.  The adapter verifies the ``token`` field in each request and
   dispatches a normalised ``InboundMessage``.

2. **Incoming webhook sender** — uses the Synology Chat External API
   (``SYNO.Chat.External``) to push messages to individual users or channels.

Authentication:
    ``token``           Token set in the Synology Chat outgoing webhook config.
                        Every inbound POST is validated against this value.
                        When empty, all requests are accepted (dev mode).
    ``incoming_token``  Token generated by Synology Chat for the incoming
                        webhook integration.  Required for ``send()`` and
                        ``ping()``.

Config keys:
    token               Outgoing webhook verification token (required for
                        verifying inbound messages)
    incoming_token      Incoming webhook token (required for send / ping)
    synology_url        Base URL of the Synology NAS, e.g.
                        ``https://mynas.example.com:5001`` (required for
                        send / ping)
    host                Webhook server bind host (default: ``"0.0.0.0"``)
    port                Webhook server port (default: 8089)
    webhook_path        URL path for the outgoing webhook endpoint (default:
                        ``"/webhook/synology_chat"``)
    bot_username        Bot's own username; messages from this user are
                        dropped to prevent echo loops

Outbound target format:
    ``user:{user_id}``        Send to a specific user (integer user ID)
    ``channel:{channel_id}``  Send to a channel (integer channel ID)
    ``{user_id}``             Bare integer string is treated as a user ID

Example config.toml::

    [channels.synology_chat]
    enabled          = true
    token            = "ENV:SYNOLOGY_OUTGOING_TOKEN"
    incoming_token   = "ENV:SYNOLOGY_INCOMING_TOKEN"
    synology_url     = "https://mynas.example.com:5001"
    port             = 8089
    webhook_path     = "/webhook/synology_chat"
"""

from __future__ import annotations

import logging
import time
from typing import Any

from cortexflow_ai.channels.base import Attachment, ChannelAdapter, InboundMessage

logger = logging.getLogger(__name__)

_SYNO_API_PATH = "/webapi/entry.cgi"
_SYNO_API = "SYNO.Chat.External"
_SYNO_METHOD = "incoming"
_SYNO_VERSION = "2"


class SynologyChatAdapter(ChannelAdapter):
    """Synology Chat adapter — outgoing webhook receiver + incoming webhook sender."""

    channel_id = "synology_chat"

    def __init__(self, config: dict[str, Any]) -> None:
        super().__init__(config)
        self._token: str = config.get("token", "")
        self._incoming_token: str = config.get("incoming_token", "")
        self._synology_url: str = config.get("synology_url", "").rstrip("/")
        self._host: str = config.get("host", "0.0.0.0")
        self._port: int = int(config.get("port", 8089))
        self._webhook_path: str = config.get("webhook_path", "/webhook/synology_chat")
        self._bot_username: str = config.get("bot_username", "")
        self._runner: Any = None

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def connect(self) -> None:
        """Start the aiohttp webhook server to receive Synology Chat messages."""
        from aiohttp import web

        app = web.Application()
        app.router.add_post(self._webhook_path, self._handle_webhook)
        app.router.add_get(self._webhook_path, self._handle_health)
        self._runner = web.AppRunner(app)
        await self._runner.setup()
        site = web.TCPSite(self._runner, self._host, self._port)
        await site.start()
        logger.info(
            "synology_chat.connected host=%s port=%d path=%s",
            self._host,
            self._port,
            self._webhook_path,
        )

    async def disconnect(self) -> None:
        """Stop the aiohttp webhook server."""
        if self._runner is not None:
            await self._runner.cleanup()
            self._runner = None
        logger.info("synology_chat.disconnected")

    # ------------------------------------------------------------------
    # Outbound
    # ------------------------------------------------------------------

    async def send(
        self,
        target: str,
        text: str,
        *,
        reply_to: str | None = None,
        attachments: list[Attachment] | None = None,
    ) -> str | None:
        """Send a message to *target* via the Synology Chat incoming webhook API.

        *target* formats:
        - ``"user:{user_id}"``  — send to a specific user (e.g. ``"user:1"``).
        - ``"channel:{id}"``    — send to a channel (e.g. ``"channel:42"``).
        - ``"{integer}"``       — bare integer string → treated as user ID.

        Returns the target on success, ``None`` on error.
        """
        if not target:
            logger.warning("synology_chat.send: target is empty")
            return None
        if not self._incoming_token or not self._synology_url:
            logger.error("synology_chat.send: incoming_token and synology_url are required")
            return None

        payload, error = self._build_payload(target, text)
        if error:
            logger.error("synology_chat.send: %s", error)
            return None

        import json as _json

        import httpx

        url = f"{self._synology_url}{_SYNO_API_PATH}"
        data = {
            "api": _SYNO_API,
            "method": _SYNO_METHOD,
            "version": _SYNO_VERSION,
            "token": self._incoming_token,
            "payload": _json.dumps(payload, separators=(",", ":")),
        }
        try:
            async with httpx.AsyncClient(verify=False) as client:
                resp = await client.post(url, data=data, timeout=15.0)
                resp.raise_for_status()
                result = resp.json()
                if not result.get("success"):
                    logger.error(
                        "synology_chat.send_error target=%s: %s", target, result
                    )
                    return None
                return target
        except Exception as exc:
            logger.error("synology_chat.send_error target=%s: %s", target, exc)
            return None

    # ------------------------------------------------------------------
    # Health check
    # ------------------------------------------------------------------

    async def ping(self) -> bool:
        """Return True if the Synology NAS is reachable and the token is set.

        Sends a dummy API request; checks for a non-5xx response (4xx can
        indicate auth issues but proves the server is up).
        """
        if not self._incoming_token or not self._synology_url:
            return False
        import httpx

        url = f"{self._synology_url}{_SYNO_API_PATH}"
        try:
            async with httpx.AsyncClient(verify=False) as client:
                resp = await client.get(
                    url,
                    params={
                        "api": _SYNO_API,
                        "method": "list",
                        "version": _SYNO_VERSION,
                        "token": self._incoming_token,
                    },
                    timeout=5.0,
                )
                return resp.status_code < 500
        except Exception:
            return False

    # ------------------------------------------------------------------
    # Webhook handlers
    # ------------------------------------------------------------------

    async def _handle_webhook(self, request: Any) -> Any:
        """Receive an outgoing webhook POST from Synology Chat."""
        from aiohttp import web

        try:
            params: dict[str, str] = dict(await request.post())
        except Exception:
            return web.Response(status=400, text="Bad request")

        # Verify token
        if self._token:
            incoming_token = params.get("token", "")
            if incoming_token != self._token:
                logger.warning("synology_chat.invalid_token")
                return web.Response(status=401, text="Unauthorized")

        text = (params.get("text") or "").strip()
        if not text:
            return web.Response(status=200, text="OK")

        username = params.get("username", "")
        if self._bot_username and username == self._bot_username:
            return web.Response(status=200, text="OK")

        user_id = params.get("user_id", "")
        channel_id = params.get("channel_id", "")
        channel_name = params.get("channel_name", "")

        try:
            ts = float(params.get("timestamp", time.time()))
        except (ValueError, TypeError):
            ts = time.time()

        thread_id = f"channel:{channel_id}" if channel_id else f"user:{user_id}"

        msg = InboundMessage(
            channel=self.channel_id,
            sender_id=user_id or username,
            sender_name=username or user_id,
            text=text,
            thread_id=thread_id,
            timestamp=ts,
            raw=dict(params),
        )

        import asyncio

        asyncio.create_task(self._dispatch(msg))
        logger.info(
            "synology_chat.message_received user=%s channel=%s",
            username,
            channel_name or channel_id,
        )
        return web.Response(status=200, text="OK")

    async def _handle_health(self, request: Any) -> Any:
        """Respond to GET requests (health / connectivity check)."""
        from aiohttp import web

        return web.Response(status=200, text="Synology Chat adapter OK")

    # ------------------------------------------------------------------
    # Payload builder
    # ------------------------------------------------------------------

    def _build_payload(
        self, target: str, text: str
    ) -> tuple[dict[str, Any], str | None]:
        """Return ``(payload_dict, error_msg)`` for the given *target*.

        Returns ``({}, error_msg)`` on parse error.
        """
        if target.startswith("user:"):
            raw_id = target[5:]
        elif target.startswith("channel:"):
            raw_id = target[8:]
            try:
                channel_id = int(raw_id)
            except ValueError:
                return {}, f"invalid channel id in target: {target!r}"
            return {"text": text, "channel_id": channel_id}, None
        else:
            raw_id = target

        try:
            user_id = int(raw_id)
        except ValueError:
            return {}, f"invalid user id in target: {target!r}"
        return {"text": text, "user_ids": [user_id]}, None

    # ------------------------------------------------------------------
    # Config schema
    # ------------------------------------------------------------------

    def get_config_schema(self) -> dict[str, Any]:
        return {
            "type": "object",
            "required": ["incoming_token", "synology_url"],
            "properties": {
                "token": {
                    "type": "string",
                    "description": "Outgoing webhook verification token from Synology Chat",
                },
                "incoming_token": {
                    "type": "string",
                    "description": "Incoming webhook token for sending messages to Synology Chat",
                },
                "synology_url": {
                    "type": "string",
                    "description": "Base URL of the Synology NAS (e.g. https://mynas.example.com:5001)",
                },
                "host": {
                    "type": "string",
                    "default": "0.0.0.0",
                    "description": "Webhook server bind host",
                },
                "port": {
                    "type": "integer",
                    "default": 8089,
                    "description": "Webhook server port",
                },
                "webhook_path": {
                    "type": "string",
                    "default": "/webhook/synology_chat",
                    "description": "URL path for the outgoing webhook endpoint",
                },
                "bot_username": {
                    "type": "string",
                    "description": "Bot's own username; messages from this user are ignored",
                },
            },
        }
